version: "3.7"
services: 
  datascience-demo:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - JUPYTER_TOKEN=password
    volumes: 
      - ./:/home/jovyan/work
    ports: 
      - "8888:8888"
    container_name: datascience-demo